//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDatabaseEntities : DbContext
    {
        public myDatabaseEntities()
            : base("name=myDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RFS_Activate> RFS_Activate { get; set; }
        public virtual DbSet<RFS_Asset> RFS_Asset { get; set; }
        public virtual DbSet<RFS_Asset_Software> RFS_Asset_Software { get; set; }
        public virtual DbSet<RFS_Department> RFS_Department { get; set; }
        public virtual DbSet<RFS_Department_2> RFS_Department_2 { get; set; }
        public virtual DbSet<RFS_Employee> RFS_Employee { get; set; }
        public virtual DbSet<RFS_Img_Asset> RFS_Img_Asset { get; set; }
        public virtual DbSet<RFS_Login> RFS_Login { get; set; }
        public virtual DbSet<RFS_Model_Asset> RFS_Model_Asset { get; set; }
        public virtual DbSet<RFS_Model_Asset_m> RFS_Model_Asset_m { get; set; }
        public virtual DbSet<RFS_Software> RFS_Software { get; set; }
        public virtual DbSet<RFS_Supplier> RFS_Supplier { get; set; }
        public virtual DbSet<RFS_Type> RFS_Type { get; set; }
        public virtual DbSet<RFS_Type_monitor> RFS_Type_monitor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ViewAllData> ViewAllData { get; set; }
        public virtual DbSet<ViewSoftware> ViewSoftware { get; set; }
        public virtual DbSet<ViewAssetMonitor> ViewAssetMonitor { get; set; }
        public virtual DbSet<viewModel_m> viewModel_m { get; set; }
        public virtual DbSet<ViewEmployee> ViewEmployee { get; set; }
        public virtual DbSet<ViewModel> ViewModel { get; set; }
        public virtual DbSet<RFS_Asset_monitor> RFS_Asset_monitor { get; set; }
        public virtual DbSet<RFS_EventLog> RFS_EventLog { get; set; }
    }
}
