//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFS_EventLog
    {
        public string asset_id { get; set; }
        public string em_id { get; set; }
        public string user { get; set; }
        public string @event { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int id { get; set; }
    }
}
