//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFS_Asset_monitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFS_Asset_monitor()
        {
            this.RFS_Asset = new HashSet<RFS_Asset>();
        }
    
        public string asset_list_m { get; set; }
        public string model_id_m { get; set; }
        public string monitor_id { get; set; }
        public Nullable<int> warranty_year { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string status { get; set; }
        public string sup_id { get; set; }
        public string user_insert { get; set; }
        public string user_update { get; set; }
        public Nullable<System.DateTime> date_insert { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public string img_id { get; set; }
        public string check_status { get; set; }
        public Nullable<int> Activate_id { get; set; }
        public byte[] img { get; set; }
    
        public virtual RFS_Activate RFS_Activate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFS_Asset> RFS_Asset { get; set; }
        public virtual RFS_Img_Asset RFS_Img_Asset { get; set; }
        public virtual RFS_Model_Asset_m RFS_Model_Asset_m { get; set; }
        public virtual RFS_Supplier RFS_Supplier { get; set; }
    }
}
