//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFS_Asset_Software
    {
        public int id { get; set; }
        public string asset_list { get; set; }
        public string software_id { get; set; }
        public string as_detail { get; set; }
    
        public virtual RFS_Asset RFS_Asset { get; set; }
        public virtual RFS_Software RFS_Software { get; set; }
    }
}
