//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_all
    {
        public string AssetID { get; set; }
        public string Service_Tag { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string User { get; set; }
        public string Level { get; set; }
        public string Location { get; set; }
        public string Monitor { get; set; }
        public string IP { get; set; }
        public string Remark { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Status { get; set; }
    }
}
