//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSoftware
    {
        public string AssetId { get; set; }
        public string Service_Tag { get; set; }
        public string Type { get; set; }
        public int Id { get; set; }
        public string SoftwareName { get; set; }
        public string Detail { get; set; }
    }
}
