//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployee
    {
        public string em_id { get; set; }
        public string em_name_th { get; set; }
        public string em_name_eng { get; set; }
        public string em_position { get; set; }
        public string dep_name { get; set; }
        public string em_level { get; set; }
        public Nullable<System.DateTime> em_start { get; set; }
        public string user_update { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
    }
}
