//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAssetMonitor
    {
        public string Asset_ID { get; set; }
        public string Monitor_ID { get; set; }
        public string Model { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string Remark { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
    }
}
